//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitarCambioMoneda.ws.Producto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codTipoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cuotasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaVencField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double montoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double montoPendienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double seguroBienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double seguroDesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double tasaInteresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoMonedaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codCliente {
            get {
                return this.codClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.codClienteField, value) != true)) {
                    this.codClienteField = value;
                    this.RaisePropertyChanged("codCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codProducto {
            get {
                return this.codProductoField;
            }
            set {
                if ((this.codProductoField.Equals(value) != true)) {
                    this.codProductoField = value;
                    this.RaisePropertyChanged("codProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codTipoProducto {
            get {
                return this.codTipoProductoField;
            }
            set {
                if ((this.codTipoProductoField.Equals(value) != true)) {
                    this.codTipoProductoField = value;
                    this.RaisePropertyChanged("codTipoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cuotas {
            get {
                return this.cuotasField;
            }
            set {
                if ((this.cuotasField.Equals(value) != true)) {
                    this.cuotasField = value;
                    this.RaisePropertyChanged("cuotas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                if ((this.fechaRegistroField.Equals(value) != true)) {
                    this.fechaRegistroField = value;
                    this.RaisePropertyChanged("fechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaVenc {
            get {
                return this.fechaVencField;
            }
            set {
                if ((this.fechaVencField.Equals(value) != true)) {
                    this.fechaVencField = value;
                    this.RaisePropertyChanged("fechaVenc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                if ((this.montoField.Equals(value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double montoPendiente {
            get {
                return this.montoPendienteField;
            }
            set {
                if ((this.montoPendienteField.Equals(value) != true)) {
                    this.montoPendienteField = value;
                    this.RaisePropertyChanged("montoPendiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double seguroBien {
            get {
                return this.seguroBienField;
            }
            set {
                if ((this.seguroBienField.Equals(value) != true)) {
                    this.seguroBienField = value;
                    this.RaisePropertyChanged("seguroBien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double seguroDes {
            get {
                return this.seguroDesField;
            }
            set {
                if ((this.seguroDesField.Equals(value) != true)) {
                    this.seguroDesField = value;
                    this.RaisePropertyChanged("seguroDes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double tasaInteres {
            get {
                return this.tasaInteresField;
            }
            set {
                if ((this.tasaInteresField.Equals(value) != true)) {
                    this.tasaInteresField = value;
                    this.RaisePropertyChanged("tasaInteres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoMoneda {
            get {
                return this.tipoMonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoMonedaField, value) != true)) {
                    this.tipoMonedaField = value;
                    this.RaisePropertyChanged("tipoMoneda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ws.Producto.IProductos")]
    public interface IProductos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ListarProductos", ReplyAction="http://tempuri.org/IProductos/ListarProductosResponse")]
        SolicitarCambioMoneda.ws.Producto.Producto[] ListarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ListarProductos", ReplyAction="http://tempuri.org/IProductos/ListarProductosResponse")]
        System.Threading.Tasks.Task<SolicitarCambioMoneda.ws.Producto.Producto[]> ListarProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ObtenerProductosporCliente", ReplyAction="http://tempuri.org/IProductos/ObtenerProductosporClienteResponse")]
        SolicitarCambioMoneda.ws.Producto.Producto[] ObtenerProductosporCliente(string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ObtenerProductosporCliente", ReplyAction="http://tempuri.org/IProductos/ObtenerProductosporClienteResponse")]
        System.Threading.Tasks.Task<SolicitarCambioMoneda.ws.Producto.Producto[]> ObtenerProductosporClienteAsync(string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ObtenerProducto", ReplyAction="http://tempuri.org/IProductos/ObtenerProductoResponse")]
        SolicitarCambioMoneda.ws.Producto.Producto ObtenerProducto(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ObtenerProducto", ReplyAction="http://tempuri.org/IProductos/ObtenerProductoResponse")]
        System.Threading.Tasks.Task<SolicitarCambioMoneda.ws.Producto.Producto> ObtenerProductoAsync(int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductosChannel : SolicitarCambioMoneda.ws.Producto.IProductos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductosClient : System.ServiceModel.ClientBase<SolicitarCambioMoneda.ws.Producto.IProductos>, SolicitarCambioMoneda.ws.Producto.IProductos {
        
        public ProductosClient() {
        }
        
        public ProductosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolicitarCambioMoneda.ws.Producto.Producto[] ListarProductos() {
            return base.Channel.ListarProductos();
        }
        
        public System.Threading.Tasks.Task<SolicitarCambioMoneda.ws.Producto.Producto[]> ListarProductosAsync() {
            return base.Channel.ListarProductosAsync();
        }
        
        public SolicitarCambioMoneda.ws.Producto.Producto[] ObtenerProductosporCliente(string cliente) {
            return base.Channel.ObtenerProductosporCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<SolicitarCambioMoneda.ws.Producto.Producto[]> ObtenerProductosporClienteAsync(string cliente) {
            return base.Channel.ObtenerProductosporClienteAsync(cliente);
        }
        
        public SolicitarCambioMoneda.ws.Producto.Producto ObtenerProducto(int codigo) {
            return base.Channel.ObtenerProducto(codigo);
        }
        
        public System.Threading.Tasks.Task<SolicitarCambioMoneda.ws.Producto.Producto> ObtenerProductoAsync(int codigo) {
            return base.Channel.ObtenerProductoAsync(codigo);
        }
    }
}
